[package]
name = "dioxus-toast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { git = "https://github.com/Dioxuslabs/dioxus", features = ["desktop"] }
dioxus-heroicons = "0.1.1"

uuid = { version = "0.8", features = ["serde", "v4"] }

[patch.crates-io]
dioxus = { git = 'https://github.com/dioxuslabs/dioxus' }