[package]
name = "dioxus-toast"
version = "0.1.2"
authors = ["YuKun Liu <mrxzx.info@gmail.com>"]
repository = "https://github.com/mrxiaozhuox/dioxus-toast"
license = "MIT"
description = "Add toast support in your dioxus project"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.2.2", features = ["html"] }
chrono = "0.4.19"
tokio = { version = "1.17.0", features = ["time"] }