[package]
name = "dioxus-toast"
version = "0.1.4"
authors = ["YuKun Liu <mrxzx.info@gmail.com>"]
repository = "https://github.com/mrxiaozhuox/dioxus-toast"
license = "MIT"
description = "Add toast support in your dioxus project"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.19", features = ["wasmbind"] }

[target.'cfg(not(any(target_arch = "wasm32", target_arch = "wasm64")))'.dependencies]
dioxus = { version = "0.2.4", features = ["desktop", "fermi"] }
tokio = { version = "1.17.0", features = ["time"] }

[target.'cfg(any(target_arch = "wasm32", target_arch = "wasm64"))'.dependencies]
dioxus = { version = "0.2.4", features = ["web", "fermi"] }
gloo-timers = { version = "0.2.3", features = ["futures"] }